name: IAT build and release pipeline


phases:
- phase: Build
  queue: Hosted VS2017
  steps:
  - powershell: |
      Install-Module psake -Force
      Install-Module psdeploy -Force
      Install-Module Pester -Force -SkipPublisherCheck
    displayName: Install prerequisites

  - powershell: |
      .\build.ps1 -Task "Analyze"
    displayName: Run Script Analyzer

  - powershell: |
      .\build.ps1 -Task "Test"
    displayName: run unit tests

  - powershell: .\build.ps1 -Task "Coverage"
    displayName: run test coverage report