name: IAT build and release pipeline


phases:
- phase: Build
  queue: Hosted VS2017
  steps:
  - powershell: |
      Install-Module psake -Force
      Install-Module psdeploy -Force
      Install-Module Pester -Force -SkipPublisherCheck
    displayName: Install prerequisites

  - powershell: |
      .\build.ps1 -Task "Analyze"
    displayName: Run Script Analyzer

  - powershell: |
      .\build.ps1 -Task "Test"
    displayName: run unit tests

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/unittests_report.xml'
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/unittests_report.xml'
      testRunTitle: 'IAT Unit Test Results'

  - powershell: .\build.ps1 -Task "Coverage"
    displayName: run test coverage report

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from **/test_coverage_report.xml'
    inputs:
      summaryFileLocation: '**/test_coverage_report.xml'
      reportDirectory: '**/'

  - powershell: .\build.ps1 -Task "PackageSxS"
    displayName: Package module in SxS directory

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '**/PackageSxS'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      OverWrite: true
